# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [8]:
my_array = np.zeros(10)
my_array[4] = 1
my_array = my_array.reshape(2, 5)
my_array

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [13]:
my_array = np.arange(10,50)
my_array = my_array[::-1]
even_elements = my_array[my_array % 2 == 0]
my_array
even_elements

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16,
       14, 12, 10])

### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [16]:
my_array = np.arange(0,9).reshape(3,3)
my_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [26]:
my_array = np.random.rand(4,3,2)
min_arr = my_array.min()
max_arr = my_array.max()
my_array, min_arr, max_arr

(array([[[0.04914361, 0.09449672],
         [0.87275758, 0.10723398],
         [0.6103686 , 0.98312221]],
 
        [[0.27496316, 0.72113788],
         [0.81362692, 0.11512014],
         [0.65128623, 0.05033364]],
 
        [[0.35190988, 0.04823972],
         [0.87584349, 0.84486866],
         [0.51920813, 0.71419916]],
 
        [[0.17789823, 0.33491498],
         [0.86764182, 0.64450805],
         [0.37472445, 0.22566545]]]),
 np.float64(0.048239716208239414),
 np.float64(0.9831222076715219))

### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [29]:
my_array_1 = np.random.rand(6,4)
my_array_2 = np.random.rand(4,3)
result = my_array_1.dot(my_array_2)
my_array_1, my_array_2, result

(array([[0.64872323, 0.5351964 , 0.41987578, 0.06709166],
        [0.26991206, 0.07661489, 0.07228297, 0.65110476],
        [0.06696325, 0.31593737, 0.08250211, 0.59600989],
        [0.36132246, 0.49142566, 0.93906037, 0.85298623],
        [0.5520642 , 0.18952995, 0.35074438, 0.71397879],
        [0.27321067, 0.68756713, 0.61493612, 0.00405002]]),
 array([[0.19749226, 0.25012134, 0.73537631],
        [0.0040538 , 0.0337867 , 0.27415245],
        [0.68894692, 0.70637922, 0.49290185],
        [0.53561046, 0.88882084, 0.6472584 ]]),
 array([[0.45549452, 0.53656603, 0.87416429],
        [0.45215377, 0.69987399, 0.67655253],
        [0.39057418, 0.61544721, 0.56229604],
        [1.17718162, 1.52846278, 1.41540062],
        [0.73385549, 1.0268444 , 1.09294636],
        [0.48257183, 0.52954428, 0.69513543]]))

Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.### 

In [36]:
my_array = np.random.rand(7,7)
mean = my_array.mean()
std = my_array.std()
normalized_array = (my_array - mean)/std
normalized_array

array([[-1.4969407 , -0.66422721,  1.20094049,  1.56423781,  0.29483324,
         0.63002342,  0.20100365],
       [-0.90834659, -0.11015606, -0.57582644,  1.20354931,  1.66807723,
        -0.10858617,  0.5586007 ],
       [-1.44782471, -1.26291677, -1.48720643, -1.36159703,  1.27187753,
        -1.37233201,  1.60555484],
       [-0.09020847,  0.70629715,  0.78871291,  0.0054974 , -0.2864757 ,
        -0.13852309,  0.52686208],
       [ 1.39889168, -1.36441939, -1.2275407 , -1.20257394,  0.94284884,
        -0.35770201, -0.20661501],
       [-1.13150552, -0.97481106, -1.43674616, -1.47327673,  0.04039854,
         0.317481  ,  0.15054267],
       [ 0.50290023,  1.49929047,  0.83164898,  1.66955337,  0.39567131,
         0.24026294,  0.47080008]])

# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ